export default {
    editor: 'editex',
    wrapper: 'editex__wrapper',
    block: 'editex__block',
    block_selected: 'editex__block_selected',
    block_selection: 'editex__block_selection',
    block_popup: 'editex__block_popup',
    block_active: 'editex__block_active',
    component: 'editex__component',
    componentText: 'editex__component-text',
    popup: 'editex__popup',
    popup_active: 'editex__popup_active',
    popupWrapper: 'editex__popup-wrapper',
    popupItem: 'editex__popup-item',
    popupItemTitle: 'editex__popup-item__title',
    popupItemIcon: 'editex__popup-item__icon',
}